from dotenv import load_dotenv
import os

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI")
DATABASE_NAME = os.getenv("DATABASE_NAME")
COLLECTION_HISTORIAL = os.getenv("COLLECTION_HISTORIAL")
COLLECTION_FABRICANTES = os.getenv("COLLECTION_FABRICANTES")
COLLECTION_ACTIVOS = os.getenv("COLLECTION_ACTIVOS")
COLLECTION_NOMBRES = os.getenv("COLLECTION_NOMBRES")
COLLECTION_LOGS = os.getenv("COLLECTION_LOGS")
COLLECTION_ALERTAS = os.getenv("COLLECTION_ALERTAS")
